# Generated by Django 2.0.2 on 2019-08-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_image', models.ImageField(upload_to='images/')),
                ('member_name', models.CharField(max_length=50)),
            ],
        ),
    ]
