# Generated by Django 2.0.2 on 2019-08-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='image',
            new_name='event_image',
        ),
        migrations.AddField(
            model_name='event',
            name='event_description',
            field=models.CharField(default='nill', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='primary_heading',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='event',
            name='secondary_heading',
            field=models.CharField(max_length=50),
        ),
    ]
